CREATE DATABASE TEST
GO 
USE TEST
GO
CREATE TABLE Persons(
PersonID INT PRIMARY KEY IDENTITY(1,1),
FirstName VARCHAR(50) NOT NULL,
Salary DECIMAL(15,2) NOT NULL,
PassportID INT 
)

GO

CREATE TABLE Passports(
PassportID INT NOT NULL,
PassportNumber VARCHAR(8)
)

GO
 INSERT INTO Persons(FirstName, Salary, PassportID)
 VALUES
 ('Roberto', 43300.00, 102),
('Tom', 56100.00, 103),
('Yana', 60200.00, 101)

GO 
INSERT INTO Passports(PassportID, PassportNumber)
VALUES
(101, 'N34FG21B'),
(102, 'K65LO4R7'),
(103, 'ZE657QP2')

GO

ALTER TABLE Passports
ADD CONSTRAINT PK_Passports
PRIMARY KEY(PassportID)

GO

ALTER TABLE Persons
ADD CONSTRAINT FK_PassportsPersons
FOREIGN KEY(PassportID) REFERENCES Passports(PassportID)

