CREATE DATABASE OnlineStore

GO

USE OnlineStore

GO

CREATE TABLE Cities(
CityID INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL
)

GO

CREATE TABLE Customers(
CustomerID INT PRIMARY KEY IDENTITY(1,1),
[Name]  VARCHAR(50) NOT NULL,
Birthday DATE,
CityID INT 
CONSTRAINT FK_Customert_Cities
FOREIGN KEY(CityID) REFERENCES Cities(CityID)
)

GO

CREATE TABLE Orders(
OrderID INT PRIMARY KEY IDENTITY(1,1),
CustomerID INT NOT NULL,
CONSTRAINT FK_Orders_Customers
FOREIGN KEY (CustomerID) REFERENCES Customers(CustomerID)
)

GO

CREATE TABLE ItemTypes(
ItemTypeID INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL
)

GO

CREATE TABLE Items(
ItemID INT PRIMARY KEY IDENTITY(1,1),
[Name] VARCHAR(50) NOT NULL,
ItemTypeID INT NOT NULL,
CONSTRAINT FK_Items_ItemTypes
FOREIGN KEY(ItemTypeID) REFERENCES ItemTypes(ItemTypeID)
)

CREATE TABLE OrderItems(
OrderID INT NOT NULL,
ItemID INT NOT NULL,
CONSTRAINT PK_OrderItems
PRIMARY KEY (OrderID, ItemID),
CONSTRAINT FK_OrderItems_Items
FOREIGN KEY(ItemID) REFERENCES Items(ItemID),
CONSTRAINT FK_OrderItems_Orders
FOREIGN KEY(OrderID) REFERENCES Orders(OrderID)
)