CREATE TABLE Users(
Id BIGINT PRIMARY KEY IDENTITY NOT NULL,
Username VARCHAR(30) NOT NULL,
Password VARCHAR(26) NOT NULL,
ProfilePicture VARBINARY(MAX),
LastLoginTime DATETIME NOT NULL,
IsDeleted BIT DEFAULT(0)
)

ALTER TABLE Users
ADD DEFAULT GETDATE()
FOR LastLoginTime