CREATE DATABASE SoftUni

GO

USE SoftUni

CREATE TABLE Towns(
Id INT PRIMARY KEY IDENTITY, 
Name NVARCHAR(50) NOT NULL
)

CREATE TABLE Addresses(
Id INT PRIMARY KEY IDENTITY, 
AddressText NVARCHAR(50) NOT NULL, 
TownId INT NOT NULL
FOREIGN KEY REFERENCES Towns(Id)
)

CREATE TABLE Departments(
Id INT PRIMARY KEY IDENTITY, 
Name NVARCHAR(50)
)

CREATE TABLE Employees(
Id INT PRIMARY KEY IDENTITY, 
FirstName NVARCHAR(50) NOT NULL, 
MiddleName NVARCHAR(50) NOT NULL, 
LastName NVARCHAR(50) NOT NULL, 
JobTitle NVARCHAR(50) NOT NULL, 
DepartmentId INT NOT NULL
FOREIGN KEY REFERENCES Departments(Id), 
HireDate DATE DEFAULT GETDATE(), 
Salary DECIMAL(15,2) CHECK (Salary < 460), 
AddressId INT NOT NULL
FOREIGN KEY REFERENCES Addresses(Id)
)